version: "3"
services:
  exercism:
    image: mrbarker/exercism-c:0.1.1
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ./.config/exercism:/root/.config/exercism
      - ./:/root/exercism
    tty: true
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
